### ISSUE TITLE
Can not obtain the skill with non-US Amazon account

### ISSUE THREAD

**Issue by xbln** [bartbutenaers/node-red-contrib-alexa-notifyme#8] opened 2020-04-29 00:14 UTC
The skill is only obtainable with US-Amazon Accounts. Please make it obtainable also for non-US accounts.

**Comment by bartbutenaers** [comment] 2020-04-29 10:54
Hi,

This is a duplicate of another [issue](https://github.com/bartbutenaers/node-red-contrib-alexa-notifyme/issues/7).  Since I cannot solve it, I will close this also.

Bart

**Closed as completed by bartbutenaers** 2020-04-29 10:54 UTC
